build:
  image: nixos/nix:2.11.0-amd64
  tags:
    - x86_64-linux
  script:
    - nix-shell ./. --argstr version "$VERSION" --run 'bash -c "\$GHC --version"'
  parallel:
    matrix:
      - VERSION: "8.10"
      - VERSION: "9.0"
      - VERSION: "9.2"
      - VERSION: "9.4"
      - VERSION: "9.6"

